//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.22 at 04:20:49 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://harvester.com")
package com.harvester.v2.config;
